name: First WorkFlow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hello Woeld"
      - name: print goodbye
        run: echo "Done Bye"
